### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by hudaprs** [hudaprs/react-native-starter#1]
These are the main things that are gonna be implemented in the project

**Common Things**
- [x] Folder Structure
- [x] Typescript
- [x] Husky
- [x] Eslint
- [x] Prettier
- [x] Module Resolver
- [x] Hook based

---

**Development Purpose**
- [x] Flipper 

---

**Infrastructure**
- [x] Architecture diagram

---

**State Management**
- [x] Redux Toolkit RTKs
- [x] Redux Toolkit Slices
- [x] Redux Persist

---

**Navigation / Routing**
- [x] React Navigation V6

---

**Style**
- [x] Native Base
- [x] Styled Component
- [x] Native Base global styles
- [x] Styled Component global styles
- [x] Image
- [x] Fonts

---

**Utilities**
- [x] Localization (i18n)
- [x] Storage (Async Storage)
- [x] Jest unit test
